### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by aplm1999** [Soberia/bypasshub#4]
after install we have this code "unable to open database file" in docker log and restart bypasshub

**Comment by Soberia** [comment]
Make sure you have permission to read and write in `bypasshub/database` directory.
If you cloned the repository as the root user, that may be the cause for the wrong permissions.

**Comment by aplm1999** [comment]
"dependency failed to start: container bypasshub-certbot-1 exited (1)" at first but at second time did it but ocserv and xray didnt work and reseted repeatly with these errors "error: cannot open file /tmp/ocserv/ocsp.der", "error: cannot open file /etc/letsencrypt/live/any-net.shop/fullchain.pem" , "nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/any-net.shop/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/any-net.shop/fullchain.pem, r) error:10000080:BIO routines::no such file)"

**Comment by Soberia** [comment]
The containers do not run as a privileged user. They can't access the files if they don't have the required permission.

Remove the `certbot/letsencrypt` directory.
```shell
sudo rm -r certbot/letsencrypt
```

Run this command to make the project directory and all the containing files and subdirectories world accessible:
```shell
sudo chmod -R 0777 /path/to/bypasshub
```

and if there are no more errors, use more stricter permissions.
